name: CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

defaults:
  run:
    shell: bash

env:
  RUSTFLAGS: --deny warnings

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install rustfmt
      uses: actions-rs/toolchain@v1
      with:
        components: rustfmt
        override: true
        toolchain: stable

    - name: Install clippy nightly
      uses: actions-rs/toolchain@v1
      with:
        components: clippy
        toolchain: nightly

    - uses: Swatinem/rust-cache@v2
      with:
        key: "clippy-nightly"

    - name: Clippy
      run: cargo +nightly clippy --all --all-targets

    - name: Format
      run: cargo fmt --all -- --check

    - name: Check for Forbidden Words
      run: |
        sudo apt-get install ripgrep
        ./bin/forbid

  core:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Rust Toolchain Components
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable

    - uses: Swatinem/rust-cache@v2

    - name: Install Bitcoin Core
      run: ./bin/install-bitcoin-core-linux

    - name: Test
      run: cargo test --all -- --ignored
